name: CI

on:
  push:
    paths:
      - Dockerfile
  pull_request:
    paths:
      - Dockerfile

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: hadolint
        uses: hadolint/hadolint-action@v3.1.0
