name: Release Docker image

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker-buildx:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: 386,amd64,arm,arm64,ppc64le,s390x

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set tag
        id: tag
        run: echo ::set-output name=tag::"${GITHUB_REF/refs\/tags\/v/}"

      - name: Build the Docker image and push
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ steps.buildx.outputs.platforms }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
